spring:
  application:
    name: gym-system
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

management:
  endpoints.web.exposure.include: 'prometheus, health'
  endpoint:
    health:
      show-details: always
      group:
        services_group.include: db, swagger
        base_group.include: diskSpace, ping
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

application:
  security:
    jwt:
      secret-key: 3WHku3bJSlAmep3DaKmBn9jbTHUsHB2AJRA8AVXNUS756lD9GBF9Sd7b/EB7etaL
      # 1800000 milliseconds = 30 minutes
      expiration: 1800000
    bruteforceprevent:
      login:
        max-attempts: 3
        # 300000 milliseconds = 5 minutes
        block-time: 300000

generate:
  random:
    password:
      length: 10
password:
  characters:
    allow: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*()

default:
  date:
    format: yyyy-MM-dd
