spring:
  application:
    name: gym-system
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

trainer-manager:
  server-name: trainer-manager
  update-training-sessions-mapping: training-session
  get-training-report-mapping: report

management:
  endpoints.web.exposure.include: 'prometheus, health'
  endpoint:
    health:
      show-details: always
      group:
        services_group.include: db, swagger
        base_group.include: diskSpace, ping
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

application:
  security:
    bruteforceprevent:
      login:
        max-attempts: 3
        # 300000 milliseconds = 5 minutes
        block-time: 300000
  fault-tolerance:
    circuit-breaker:
      timeout: 30000

generate:
  random:
    password:
      length: 10
password:
  characters:
    allow: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*()

default:
  date:
    format: yyyy-MM-dd