spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/gymsystem}
#    username: root
#    password: toor
    hikari:
      maximum-pool-size: 1

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  liquibase:
    change-log: classpath:db/changelog/test-changelog.yaml

  activemq:
#    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
#    user: admin
#    password: admin
    pool:
      enabled: false

activemq:
  query:
    name:
      trainerworkload: "trainer-workload"
      report: "report"

application:
  security:
    jwt:
      secret-key: 3WHku3bJSlAmep3DaKmBn9jbTHUsHB2AJRA8AVXNUS756lD9GBF9Sd7b/EB7etaL
      # 1800000 milliseconds = 30 minutes
      expiration: 60000
    bruteforceprevent:
      login:
        max-attempts: 3
        # 300000 milliseconds = 5 minutes
        block-time: 10000000



