spring:
  application:
    name: trainer-manager
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/trainermanagerdb}
      auto-index-creation: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

