spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: admin
    password: admin
    pool:
      enabled: false
  data:
    mongodb:
      collections:
        report:
          test-data-filepath: classpath:/db/data/test/reports.json

activemq:
  query:
    name:
      trainerworkload: "trainer-workload"
      report: "report"

application:
  security:
    jwt:
      secret-key: 3WHku3bJSlAmep3DaKmBn9jbTHUsHB2AJRA8AVXNUS756lD9GBF9Sd7b/EB7etaL
      # 1800000 milliseconds = 30 minutes
      expiration: 1800000
